name: Ng Cheuk-fung
link: cheuk-fung.github.io
author: Ng Cheuk-fung
email: cheukfungplus@gmail.com
github: cheuk-fung
twitter: leewings
disqus: cheuk-fung

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
permalink: none
