pygments    : true
permalink   : none
markdown    : maruku

name        : The Stars My Destination
author      : Ng Cheuk-fung
email       : osideal@gmail.com
link        : leewings.github.com
disqus      : cheuk-fung

maruku:
    use_tex: true
    use_divs: true
    png_engine: blahtex
    png_dir: images/latex/
    png_url: /images/latex/
