name: Ng Cheuk-fung
link: cheuk-fung.github.io
author: Ng Cheuk-fung
email: cheukfungplus@gmail.com
github: cheuk-fung
twitter: leewings
disqus: cheuk-fung

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables", "strikethrough", "with_toc_data"]

pygments: true
permalink: none
