pygments    : true
permalink   : none
markdown    : maruku

name        : The Stars My Destination
author      : Ng Cheuk-fung
email       : osideal@gmail.com
link        : leewings.github.com
disqus      : cheuk-fung
